### ISSUE TITLE
Ask for permissions

### ISSUE THREAD

**Issue by eikebartels** [davidchang/angular-facebook-utils#15]
Hey, 

how can I use your lib to ask for permissions on the fly? 
- login 
- do something 
- ask for additional permissions 

Thanks for the easy lib!

**Comment by nomoreboredom** [comment]
After a couple of trying I have managed to solve this:
You should add permissons to:
constant('facebookConfigSettings', {
        'appID' : '',
    'routingEnabled' : true,  
    'channelFile'    : 'channel.html',
    'permissions'    : "email",
})
And change the function as the following:
user.api('/me').then(function(response) {
.............
},{scope: 'email'});
I hope it helps!
