### ISSUE TITLE
Defining Module Name

### ISSUE THREAD

**Issue by hybrisCole** [davidchang/angular-facebook-utils#4]
I changed from:

angular.module("facebookUtils", []);
    angular.module("angular-facebook-utils").run([ "$templateCache", function($templateCache) {

To:

angular.module("facebookUtils", []);
    angular.module("facebookUtils").run([ "$templateCache", function($templateCache) {

And it started working, any ideas about this? Want me to do a pull request?

Regards!

**Comment by hasdavidc** [comment]
@hybrisCole - thanks! I completely missed that. Please do put in a PR and I'll get to merging it.

Those files are actually generated after running Grunt build, so the change would be in https://github.com/davidchang/angular-facebook-utils/blob/master/Gruntfile.js#L81 to "facebookUtils", then a grunt build to update both the unminified and minified versions.

**Comment by hasdavidc** [comment]
@hybrisCole - sorry, I didn't hear back from you and got to fixing it myself. It'll be a part of the next release. Thanks for bringing it to my attention.

**Comment by hybrisCole** [comment]
np man sorry about that, been kinda busy hehe
