### ISSUE TITLE
Permissions not passed to the SDK.

### ISSUE THREAD

**Issue by cavarzan** [davidchang/angular-facebook-utils#9]
Hi,

I configure some facebook's permissions in the angular-facebook-utils to get the email permission when the user click to login.

But the permission is not sended to the Facebook (o got `undefined`).

I fix the error changing the line 110:

from: `scope: _self.permissions`
to : `scope: SDK.permissions`

Since the _self variable from SDK doesn't contain the permissions array.

Did someone have this issue too?

**Comment by hasdavidc** [comment]
@cavarzan - sorry to hear you had some issues. I'm about to push a much better version (though heavily refactored and breaking), available currently in the 1.1.0 branch
